---
title: "ades2006"
author: "mulifeng"
date: "2021/7/11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(R2jags)
```



```{r}
model_bnma_fixed <- function(){
  for (i in 1:N) {
    logit(p[i]) <- mu[s[i]] + d[t[i]] - d[b[i]]  # model
    r[i] ~ dbin(p[i], n[i])  # binominal likelihood
  }
  
  # vague priors for 24 trial baselines
  for (j in 1:NS) {
    mu[j] ~ dnorm(0, 0.0001)
  }
  
  # vague priors for basic parameters
  d[1] <- 0
  for (k in 2:NT) {
    d[k] ~ dnorm(0, 0.0001)
  }
  
}



model_bnma_random <- function(){
  for (i in 1:N) {
    logit(p[i]) <- mu[s[i]] + delta[i] * (1-equals(t[i], b[i]))  # model
    r[i] ~ dbin(p[i], n[i])  # binominal likelihood
    # random effect distributions of trial-specific LORs
    # means of distributions
    delta[i] ~ dnorm(md[i], tau)
    md[i] <- d[t[i]] - d[b[i]]
  }
  
  # vague priors for 24 trial baselines
  for (j in 1:NS) {
    mu[j] ~ dnorm(0, .0001)
  }
  
  # vague priors for basic parameters
  d[1] <- 0
  for (k in 2:NT) {
    d[k] ~ dnorm(0, .0001)
  }
  
  # vague prior for RE standard deviation
  sd ~ dunif(0, 2) 
  tau <- 1/pow(sd, 2)
  
}
```



```{r}
data_bnma <- tribble(
~s,	~t,	~r,	~n,	~b,
1,	1,	79,	702,	1,
1,	2,	77,	694,	1,
2,	1,	18,	671,	1,
2,	2,	21,	535,	1,
3,	1,	8,	116,	1,
3,	2,	19,	146,	1,
4,	1,	75,	731,	1,
4,	3,	363,	714,	1,
5,	1,	2,	106,	1,
5,	3,	9,	205,	1,
6,	1,	58,	549,	1,
6,	3,	237,	1561,	1,
7,	1,	0,	33,	1,
7,	3,	9,	48,	1,
8,	1,	3,	100,	1,
8,	3,	31,	98,	1,
9,	1,	1,	31,	1,
9,	3,	26,	95,	1,
10,	1,	6,	39,	1,
10,	3,	17,	77,	1,
11,	1,	64,	642,	1,
11,	3,	107,	761,	1,
12,	1,	5,	62,	1,
12,	3,	8,	90,	1,
13,	1,	20,	234,	1,
13,	3,	34,	237,	1,
14,	1,	95,	1107,	1,
14,	3,	134,	1031,	1,
15,	1,	15,	187,	1,
15,	3,	35,	504,	1,
16,	1,	78,	584,	1,
16,	3,	73,	675,	1,
17,	1,	69,	1177,	1,
17,	3,	54,	888,	1,
18,	1,	9,	140,	1,
18,	3,	23,	140,	1,
18,	4,	10,	138,	1,
19,	1,	0,	20,	1,
19,	4,	9,	20,	1,
20,	2,	20,	49,	2,
20,	3,	16,	43,	2,
21,	2,	11,	78,	2,
21,	3,	12,	85,	2,
21,	4,	29,	170,	2,
22,	2,	7,	66,	2,
22,	4,	32,	127,	2,
23,	3,	12,	76,	3,
23,	4,	20,	74,	3,
24,	3,	9,	55,	3,
24,	4,	3,	26,	3
)
s <- data_bnma$s
t <- data_bnma$t
r <- data_bnma$r
n <- data_bnma$n
b <- data_bnma$b
NS <- 24  # 总共纳入24项研究
N <- 50  # 所有研究共50个臂arms
NT <- 4  # 共涉及4种干预
```

```{r}
jags_dat <- list('s', 't', 'r', 'n', 'b', 'NS', 'N', 'NT')
jags_params <- c("d")
```


```{r}


bayes.mod.fixed <- jags(data = jags_dat, #inits = inits,
                      parameters.to.save = jags_params, n.chains = 3, n.iter = 20000,
                      n.burnin = 10000, model.file = model_bnma_fixed)

bayes.mod.random <- jags(data = jags_dat, #inits = inits,
                      parameters.to.save = jags_params, n.chains = 3, n.iter = 20000,
                      n.burnin = 10000, model.file = model_bnma_random)

```

# 查看固定效应模型结果
```{r}
bayes.mod.fixed
```

# 查看随机效应模型结果
```{r}
bayes.mod.random
```

# 检查固定效应模型收敛情况
```{r}
bayes.mod.fixed.mcmc <- as.mcmc(bayes.mod.fixed)
summary(bayes.mod.fixed.mcmc)
plot(bayes.mod.fixed.mcmc)
coda::autocorr.plot(bayes.mod.fixed.mcmc)

```

# 检查随机效应模型收敛情况
```{r}
bayes.mod.random.mcmc <- as.mcmc(bayes.mod.random)
summary(bayes.mod.random.mcmc)
plot(bayes.mod.random.mcmc)
coda::autocorr.plot(bayes.mod.random.mcmc)
```

