---
title: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE)
```

```{r, echo=FALSE, warnings=FALSE, message=FALSE, fig.align='center'}
# 聚多卡醇中标信息分析

library(openxlsx)
library(ggplot2)
library(dplyr)
library(ggrepel)

data <- read.xlsx("jdkczbxx.xlsx", colNames = TRUE)  # 聚多卡醇中标信息查询
colnames(data) <- c('genname', 'brandname', 'dosageForm', 'specification', 'bzzhb',
                    'unit', 'price', 'zlcc', 'manufacturer', 'biddingEnterprise',
                    'provice', 'date', 'remarks', 'source') 
# as.Date(data$date, origin = '1899-12-30')  # 为什么不是1970-01-01？

# windows()
# x11()
ggplot(data, aes(x = as.Date(data$date, origin = '1899-12-30'), 
                 y = price/bzzhb, colour = specification)) +
  geom_point(aes(shape = manufacturer),size = 3, alpha = 0.8) +
  geom_text_repel(aes(label = paste(provice, price/bzzhb)), size = 4, colour = "black",
                  arrow = arrow(length = unit(0.008, "npc")),
                  box.padding = 1) +
  geom_smooth(aes(group = specification, colour = specification), alpha = 0.3) +
  xlab("中标日期") +
  ylab("中标价格（元/支）") +
  scale_shape_discrete('生产企业') +
  scale_colour_discrete('规格')
```


