---
title: ""
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE)
```


```{r, echo=FALSE, warnings=FALSE, messages=FALSE, fig.align='center', fig.width=11}
# 聚明胶肽绘图
library(ggplot2)
library(openxlsx)
library(dplyr)
library(ggthemes)

data <- read.xlsx("190713.xlsx")

# 箱线图
p <- ggplot(data) +
  geom_boxplot(aes(x = product, y = xhd, fill = batch)) +
  # geom_hline(yintercept = 1.5) +
  # geom_hline(yintercept = 2.9) +
  annotate("rect", ymin = 0.015, ymax = 0.029, xmin = 0, xmax = 6, fill = "blue", alpha = 0.1) +
  ylab("Acylation degree") + 
  xlab("categories") +
  scale_x_discrete(breaks = c("A", "B", "C", "D", "xuepai"),
                   labels = c("A", "B", "C", "D", "xuepai")) +
  scale_y_continuous(breaks = c(0.01, 0.015, 0.02, 0.025, 0.03),
                     labels = scales::percent,
                     limits = c(0.0145, 0.03))+
  theme_light() +
  ggtitle("雪派与4种市售产品的酰化度比较") +
  theme_wsj()

# Acylation degree
p1 <- ggplot(data, aes(x = num, y = xhd, fill = product)) + 
  geom_bar(position = "dodge", stat = "identity") + 
  scale_fill_manual(values = c("#330099","#6699FF","#9966CC","#660066","#00FF00"),
                    name = "categories",
                    breaks = c("A", "B", "C", "D", "xuepai"),
                    labels = c("A", "B", "C", "D", "xuepai")) +
  scale_x_discrete(
    breaks = c("A1", "A2","A3","B1","B2","B3","C1","C2","C3","D1", "D2", "D3", "xp1", "xp2","xp3"),
    labels = c("A1", "A2","A3","B1","B2","B3","C1","C2","C3","D1", "D2", "D3", "xuepai-1", "xuepai-2", "xuepai-3")) +
  scale_y_continuous(limits = c(0, 0.03),
    breaks = c(0.01, 0.015, 0.02, 0.025, 0.03),
                     labels = scales::percent) +
  ylab("Acylation degree") + 
  xlab("categories") +
  ggtitle("雪派与4种市售产品的酰化度比较") +
  annotate("rect", ymin = 0.015, ymax = 0.029, xmin = 0, xmax = 16, fill = "red", alpha = 0.05) +
  theme_wsj()
p1


# crosslinking agent
p2 <- ggplot(data, aes(x = num, y = jljcl, fill = product)) + 
  geom_bar(position = "dodge", stat = "identity") + 
  scale_fill_manual(values = c("#99CCCC","#669999","#CCFFCC","#99CC66","#00FF00"),
                    name = "categories",
                    breaks = c("A", "B", "C", "D", "xuepai"),
                    labels = c("A", "B", "C", "D", "xuepai")) +
  scale_x_discrete(
    breaks = c("A1", "A2","A3","B1","B2","B3","C1","C2","C3","D1", "D2", "D3", "xp1", "xp2","xp3"),
    labels = c("A1", "A2","A3","B1","B2","B3","C1","C2","C3","D1", "D2", "D3", "xuepai-1", "xuepai-2", "xuepai-3")) +
  scale_y_continuous(limits = c(0, 520),
                     breaks = c(0, 100, 200, 300, 400, 500)) +
  ylab("crosslinking agent residues") + 
  xlab("categories") +
  ggtitle("雪派与4种市售产品的交联剂残留量比较") +
    theme_wsj()
p2


# weight-average molecular weight
p3 <- ggplot(data, aes(x = num, y = zjfzl, fill = product)) + 
  geom_bar(position = "dodge", stat = "identity") + 
  scale_fill_manual(values = c("#9999CC","#666699","#9999FF","#CCCCFF","#00FF00"),
                    name = "categories",
                    breaks = c("A", "B", "C", "D", "xuepai"),
                    labels = c("A", "B", "C", "D", "xuepai")) +
  scale_x_discrete(
    breaks = c("A1", "A2","A3","B1","B2","B3","C1","C2","C3","D1", "D2", "D3", "xp1", "xp2","xp3"),
    labels = c("A1", "A2","A3","B1","B2","B3","C1","C2","C3","D1", "D2", "D3", "xuepai-1", "xuepai-2", "xuepai-3")) +
  scale_y_continuous(limits = c(0, 4),
                     breaks = c(0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4)) +
  ylab("weight-average molecular weight") + 
  xlab("categories") +
  ggtitle("雪派与4种市售产品的重均分子量比较") +
  annotate("rect", ymin = 2.75, ymax = 3.85, xmin = 0, xmax = 16, fill = "blue", alpha = 0.1) +
    theme_wsj()
p3


# Free amino groups
p4 <- ggplot(data, aes(x = num, y = ylaj, fill = product)) + 
  geom_bar(position = "dodge", stat = "identity") + 
  scale_fill_manual(values = c("#789262","#549688","#48C0A3","#7BCFA6","#00FF00"),
                    name = "categories",
                    breaks = c("A", "B", "C", "D", "xuepai"),
                    labels = c("A", "B", "C", "D", "xuepai")) +
  scale_x_discrete(
    breaks = c("A1", "A2","A3","B1","B2","B3","C1","C2","C3","D1", "D2", "D3", "xp1", "xp2","xp3"),
    labels = c("A1", "A2","A3","B1","B2","B3","C1","C2","C3","D1", "D2", "D3", "xuepai-1", "xuepai-2", "xuepai-3")) +
  scale_y_continuous(limits = c(0, 0.75),
                     breaks = c(0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7)) +
  ylab("Free amino groups") + 
  xlab("categories") +
  ggtitle("雪派与4种市售产品的游离氨基值比较") +
  annotate("rect", ymin = 0.5, ymax = 0.65, xmin = 0, xmax = 16, fill = "blue", alpha = 0.1) +
    theme_wsj()
p4


library(cowplot)
p <- plot_grid(p1, p2, p3, p4, ncol = 2,
               labels = paste(LETTERS[1:4], ")"),
               label_size = 20)

```
