---
title: "Monty Hall problem"
author: "Mu Lifeng"
date: "2019/11/25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(grid)
```

```{r}
data <- data.frame(x = c(rep(1:3, each = 4)), 
                         y = c(1, 3, 4.5, 5.5, 1, 2.5, 3.5, 5, 0.5, 1.5, 3, 5), 
                   width = c(rep(1, 12)),
                   heigh = c(2, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2),
                         label = c("C-B", "B-C", "A-C", "A-B", "C-A", "B-C",
                                   "B-A", "A-C", "C-B", "C-A", "B-A", "A-B"),
                   prob = c("1/3*1", "1/3*1", "1/3*1/2", "1/3*1/2",
                            "1/3*1", "1/3*1/2", "1/3*1/2", "1/3*1",
                            "1/3*1/2", "1/3*1/2", "1/3*1", "1/3*1"))
```



```{r}
ggplot(data, aes(x = x, y = y)) +
  geom_tile(aes(width = width, height = heigh, fill = label)) +
  geom_text(aes(label = paste(label, "\n", prob))) +
  #ylim(-4, 7) +
  annotate("text", x=1:3, y = 6.5, 
           label = c("汽车在A门后(1/3)", "汽车在B门后(1/3)", "汽车在C门后(1/3)")) +
  scale_fill_discrete(name = "", label = c("A-B 选A开B", "A-C 选A开C", "B-A 选B开A",
                         "B-C 选B开C", "C-A 选C开A", "C-B 选C开B")) +
  theme_bw() +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank())



```

```{r, echo=FALSE}
grid.text("P(A|A-B) = 1/6/(1/6+1/3) = 1/3\nP(B|A-B) = 0\nP(C|A-B) = 1/3/(1/6+1/3) = 2/3\nP(A|A-C) = 1/6/(1/6+1/3) = 1/3\nP(B|A-C) = 1/3/(1/6+1/3) = 2/3\nP(C|A-B) = 0\nP(A|B-A) = 0\nP(B|B-A) = 1/6/(1/6+1/3) = 1/3\nP(C|B-A) = 1/3/(1/6+1/3) = 2/3\nP(A|B-C) = 1/3/(1/6+1/3) = 2/3\nP(B|B-C) = 1/6/(1/6+1/3) = 1/3\nP(C|B-C) = 0\nP(A|C-A) = 0\nP(B|C-A) = 1/3/(1/6+1/3) = 2/3\nP(C|C-A) = 1/6/(1/6+1/3) = 1/3\nP(A|C-B) = 1/3/(1/6+1/3) = 2/3\nP(B|C-B) = 0\nP(C|C-B) = 1/6/(1/6+1/3) = 1/3\n在主持人打开其中的一扇门之前，选中汽车\n的概率为1/3，选A开B后汽车在A门后的概率\n仍为1/3，汽车在C门后的概率增加至2/3，所以\n若更换最初的选择可以提高选中汽车的概率", x = 0, hjust = 0, gp = gpar(cex=2))
```

